/**
 * Auto-generated from the live WordPress site via /wp-json/wp/v2/formation.
 * 61 individual formation pages from the custom post type "formation".
 * Regenerate with: powershell scripts/generate-formations-ts.ps1
 */

export type FormationCategory =
  | "safety-day"
  | "habilitation-electrique"
  | "afgsu"
  | "secourisme"
  | "securite-incendie"
  | "ergonomie"
  | "prevention";

export type FormationEntry = {
  slug: string;
  title: string;
  excerpt: string;
  image: string;
  category: FormationCategory;
  categoryLabel: string;
  categoryHref: string;
  date: string;
};

export const formationEntries: FormationEntry[] = [
  {
    slug: "formation-afgsu1",
    title: "Formation AFGSU 1",
    excerpt: "AFGSU niveau 1 destinée aux personnels non soignants exerçant en établissement de santé : gestes de premiers secours, urgences vitales, risques sanitaires. Conforme à l'arrêté du 1er juillet 2019.",
    image: "/formations/formation-afgsu1.jpg",
    category: "afgsu",
    categoryLabel: "AFGSU",
    categoryHref: "/nos-formations-afgsu",
    date: "2025-06-30T15:00:06",
  },
  {
    slug: "formation-afgsu2",
    title: "Formation AFGSU 2",
    excerpt: "AFGSU niveau 2 pour les professionnels de santé : infirmiers, aides-soignants, médecins, sages-femmes, kinés. Prise en charge des détresses vitales et matériel d'urgence.",
    image: "/formations/formation-afgsu2.jpg",
    category: "afgsu",
    categoryLabel: "AFGSU",
    categoryHref: "/nos-formations-afgsu",
    date: "2025-07-01T10:38:25",
  },
  {
    slug: "formation-recyclage-afgsu1",
    title: "Formation remise à niveau AFGSU 1",
    excerpt: "Remise à niveau AFGSU niveau 1, obligatoire tous les 4 ans pour conserver l'attestation. Mise à jour des recommandations, gestes techniques et urgences sanitaires.",
    image: "/formations/formation-recyclage-afgsu1.jpg",
    category: "afgsu",
    categoryLabel: "AFGSU",
    categoryHref: "/nos-formations-afgsu",
    date: "2025-06-30T16:38:18",
  },
  {
    slug: "formation-recyclage-afgsu2",
    title: "Formation remise à niveau AFGSU 2",
    excerpt: "Remise à niveau AFGSU niveau 2 tous les 4 ans pour les professionnels de santé : actualisation des protocoles, prise en charge des détresses vitales et nouveautés réglementaires.",
    image: "/formations/formation-recyclage-afgsu2.jpg",
    category: "afgsu",
    categoryLabel: "AFGSU",
    categoryHref: "/nos-formations-afgsu",
    date: "2025-07-01T11:10:45",
  },
  {
    slug: "formation-gestes-et-postures",
    title: "Formation gestes et postures",
    excerpt: "Réduire les TMS et arrêts de travail liés aux postures, port de charges et travail sur écran. Analyse de poste, échauffements et bons réflexes appliqués à votre activité.",
    image: "/formations/formation-gestes-et-postures.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2025-07-03T15:53:52",
  },
  {
    slug: "formation-gestes-et-postures-en-creche",
    title: "Formation gestes et postures en crèche",
    excerpt: "Gestes et postures spécifiques aux professionnels de la petite enfance : portage d'enfants, mobilier bas, change, repas. Prévention des lombalgies et TMS en crèche.",
    image: "/formations/formation-gestes-et-postures-en-creche.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2025-07-07T09:12:42",
  },
  {
    slug: "formation-gestes-et-postures-etablissements-de-soins-ehpad",
    title: "Formation gestes et postures établissement de soins EHPAD",
    excerpt: "Manutention de personnes à mobilité réduite en EHPAD et établissements de soins : transferts, rehaussements, utilisation des aides techniques. Prévention TMS du personnel soignant.",
    image: "/formations/formation-gestes-et-postures-etablissements-de-soins-ehpad.png",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2025-07-07T09:22:50",
  },
  {
    slug: "formation-prap-2s-sanitaire-et-social",
    title: "PRAP 2S ALM (Sanitaire et Sociale)",
    excerpt: "PRAP 2S ALM (Sanitaire et Social), 28h en 2 × 2 jours non consécutifs. Certificat d'acteur PRAP 2S ALM délivré à l'issue de l'évaluation certificative INRS (valable 24 mois). Pour EHPAD, hôpital, handicap, aide à domicile : manutention de personnes, prévention TMS, démarche participative.",
    image: "/formations/formation-prap-2s-sanitaire-et-social.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2025-07-07T10:32:55",
  },
  {
    slug: "formation-prap-ibc",
    title: "PRAP IBC (Industrie Bâtiment Commerce)",
    excerpt: "PRAP IBC (Industrie, BTP, Commerce, Bureau). Certificat d'acteur PRAP IBC délivré à l'issue (valable 24 mois). Chaque salarié devient acteur de sa prévention TMS : observation, analyse, propositions d'amélioration.",
    image: "/formations/formation-prap-ibc.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2025-07-04T09:18:11",
  },
  {
    slug: "formation-prevention-des-tms-troubles-musculosquelettiques",
    title: "Formation prévention des TMS",
    excerpt: "Prévention des troubles musculo-squelettiques (TMS), 1ère cause de maladie professionnelle en France. Identifier les contraintes, ajuster les postes, ancrer les bons gestes.",
    image: "/formations/formation-prevention-des-tms-troubles-musculosquelettiques.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2025-07-04T11:27:32",
  },
  {
    slug: "habilitation-electrique-br-b1-b2-bc",
    title: "Habilitation électrique BR B1 B2 BC",
    excerpt: "Habilitation électrique BR (chargé d'interventions générales BT), B1/B2 (exécutant/chargé de travaux), BC (consignation). Pour électriciens — partie théorique et pratique sur platine.",
    image: "/formations/habilitation-electrique-br-b1-b2-bc.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2025-07-02T14:12:08",
  },
  {
    slug: "habilitation-electrique-bs-be-manoeuvre",
    title: "Habilitation électrique BS BE Manœuvre",
    excerpt: "Habilitation BS (interventions élémentaires hors tension : ampoule, prise, interrupteur) et BE Manœuvre (réarmement, mise en marche). Pour non-électriciens. Conforme NF C18-510.",
    image: "/formations/habilitation-electrique-bs-be-manoeuvre.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2025-07-02T10:40:35",
  },
  {
    slug: "habilitation-electrique-h0-b0",
    title: "Habilitation électrique H0 B0",
    excerpt: "Habilitation B0 / H0 / H0V pour les non-électriciens travaillant à proximité d'installations électriques (basse et haute tension). Conforme à la norme NF C18-510.",
    image: "/formations/habilitation-electrique-h0-b0.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2025-07-02T09:28:49",
  },
  {
    slug: "habilitation-electrique-photovoltaique-bp",
    title: "Habilitation électrique BP photovoltaïque",
    excerpt: "Habilitation BP pour interventions sur installations photovoltaïques : modules PV, onduleurs, coffrets DC/AC. Spécificités du courant continu, prévention de l'arc électrique.",
    image: "/formations/habilitation-electrique-photovoltaique-bp.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2025-07-03T12:23:36",
  },
  {
    slug: "recyclage-habilitation-electrique-br-b1-b2-bc",
    title: "Recyclage Habilitation électrique BR B1 B2 BC",
    excerpt: "Recyclage électricien BR / B1 / B2 / BC tous les 3 ans (recommandation NF C18-510 et INRS) : mise à jour des évolutions normatives, retour d'expérience, pratique sur platine.",
    image: "/formations/recyclage-habilitation-electrique-br-b1-b2-bc.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2025-07-02T14:47:04",
  },
  {
    slug: "recyclage-habilitation-electrique-bs-be",
    title: "Recyclage Habilitation électrique BS BE Manœuvre",
    excerpt: "Recyclage BS et BE Manœuvre tous les 3 ans : rappels sur les interventions de remplacement et raccordement hors tension, manœuvres autorisées, gestes de premier secours.",
    image: "/formations/recyclage-habilitation-electrique-bs-be.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2025-07-02T12:00:17",
  },
  {
    slug: "recyclage-habilitation-electrique-h0-b0",
    title: "Recyclage Habilitation électrique H0 B0",
    excerpt: "Recyclage B0 / H0 / H0V pour non-électriciens, tous les 3 ans : rappel des risques électriques, distances de sécurité, conduite à tenir en cas d'accident électrique.",
    image: "/formations/recyclage-habilitation-electrique-h0-b0.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2025-07-02T10:06:29",
  },
  {
    slug: "formation-cse-chsct",
    title: "Formation CSE CHSCT (-300 salariés) Comité Social Economique - Comité d’Hygiène, de Sécurité, des Conditions de Travail",
    excerpt: "Formation obligatoire des membres CSE / CSSCT (L.2315-18 du Code du travail) : santé-sécurité, analyse des risques, enquêtes accidents, droit d'alerte. 3 ou 5 jours selon effectif.",
    image: "/formations/formation-cse-chsct.png",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2025-07-07T14:59:58",
  },
  {
    slug: "formation-gestion-des-situations-durgence-en-creche",
    title: "Formation Gestes d'Urgence Petite Enfance",
    excerpt: "Réagir face aux urgences en crèche : convulsions, étouffement, traumatismes, fièvre. Protocole d'alerte, communication avec les parents, coordination avec les secours.",
    image: "/formations/formation-gestion-des-situations-durgence-en-creche.jpg",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2025-07-07T12:00:48",
  },
  {
    slug: "formation-hygiene-alimentaire-haccp",
    title: "Formation HACCP — Hygiène alimentaire",
    excerpt: "Méthode HACCP obligatoire en restauration commerciale et collective (arrêté du 5 octobre 2011) : 7 principes, plan de maîtrise sanitaire, traçabilité, chaîne du froid.",
    image: "/formations/formation-hygiene-alimentaire-haccp.png",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2025-07-07T14:05:39",
  },
  {
    slug: "formation-menace-terroriste",
    title: "Formation menace terroriste",
    excerpt: "Préparer ses équipes à une attaque terroriste : doctrine S'échapper / Se cacher / Alerter, repérage des signaux faibles, mises en situation et coordination avec les forces de l'ordre.",
    image: "/formations/formation-menace-terroriste.png",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2025-07-07T11:06:49",
  },
  {
    slug: "formation-ppms-plan-particulier-mise-en-surete",
    title: "Formation PPMS — Gestion des situations d'urgence",
    excerpt: "PPMS — Plan Particulier de Mise en Sûreté pour établissements scolaires et crèches : risques majeurs, intrusion, confinement, évacuation, exercice annuel obligatoire.",
    image: "/formations/formation-ppms-plan-particulier-mise-en-surete.jpg",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2025-07-07T11:54:54",
  },
  {
    slug: "formation-travaux-en-hauteur",
    title: "Formation travail en hauteur — utilisation des EPI",
    excerpt: "Prévention des chutes de hauteur, 2ème cause d'accidents mortels au travail : EPI antichute (harnais, longes), points d'ancrage, échafaudages, PEMP. Conforme R4323-58.",
    image: "/formations/formation-travaux-en-hauteur.png",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2025-07-07T11:30:15",
  },
  {
    slug: "safety-day-gestes-et-postures",
    title: "Safety Day – Gestes et postures",
    excerpt: "Atelier gestes et postures en Safety Day : sensibilisation aux TMS, échauffements collectifs, démonstrations pratiques sur le port de charges et le travail sur écran.",
    image: "/formations/safety-day-gestes-et-postures.jpg",
    category: "safety-day",
    categoryLabel: "Safety Day",
    categoryHref: "/formations-safety-day",
    date: "2025-07-08T12:17:15",
  },
  {
    slug: "safety-day-incendie",
    title: "Safety day Incendie",
    excerpt: "Atelier incendie en Safety Day avec bac à flammes écologique ou extincteur laser : manipulation d'extincteurs, classes de feu, départ de feu, évacuation en équipe.",
    image: "/formations/safety-day-incendie.jpg",
    category: "safety-day",
    categoryLabel: "Safety Day",
    categoryHref: "/formations-safety-day",
    date: "2025-07-07T15:40:43",
  },
  {
    slug: "safety-day-risques-routiers",
    title: "Safety Day – Risques routiers",
    excerpt: "Atelier risques routiers, 1ère cause de mortalité au travail : distance de freinage, alcool et stupéfiants, fatigue, téléphone au volant, conduite préventive sur route.",
    image: "/formations/safety-day-risques-routiers.jpg",
    category: "safety-day",
    categoryLabel: "Safety Day",
    categoryHref: "/formations-safety-day",
    date: "2025-07-08T12:32:54",
  },
  {
    slug: "safety-day-secourisme-premiers-secours",
    title: "Safety Day – Premiers secours",
    excerpt: "Atelier premiers secours en Safety Day : PLS, alerter, protéger, examiner. Une initiation accessible à tous pour ancrer les bons réflexes face à un malaise ou une chute.",
    image: "/formations/safety-day-secourisme-premiers-secours.jpg",
    category: "safety-day",
    categoryLabel: "Safety Day",
    categoryHref: "/formations-safety-day",
    date: "2025-07-08T09:06:13",
  },
  {
    slug: "formation-defibrillateur",
    title: "Formation défibrillateur (DAE)",
    excerpt: "Maîtriser le défibrillateur automatisé externe (DAE / DSA) en milieu professionnel : reconnaître l'arrêt cardiaque, alerter, RCP, mise en œuvre du DAE en moins de 3 minutes.",
    image: "/formations/formation-defibrillateur.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-07-01T12:33:40",
  },
  {
    slug: "formation-formateur-sst",
    title: "Formation de formateur SST",
    excerpt: "Devenez formateur SST certifié INRS : pédagogie active, animation de groupe, maîtrise du référentiel V8. MAC tous les 36 mois pour conserver la certification.",
    image: "/formations/formation-formateur-sst.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-06-30T14:23:46",
  },
  {
    slug: "formation-gqs-gestes-qui-sauvent",
    title: "Atelier GQS — Gestes Qui Sauvent",
    excerpt: "Formation Gestes Qui Sauvent (GQS) — 2h homologuée Ministère de l'Intérieur : alerter, masser, défibriller. Sensibilisation grand public et tous publics en entreprise.",
    image: "/formations/formation-gqs-gestes-qui-sauvent.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-06-30T14:20:54",
  },
  {
    slug: "formation-mac-formateur-sst",
    title: "Recyclage formateur SST (MAC FO SST)",
    excerpt: "MAC formateur SST — tous les 36 mois pour maintenir le certificat de formateur INRS : actualisation du référentiel V8, retours d'expérience, évaluation.",
    image: "/formations/formation-mac-formateur-sst.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-06-30T11:31:02",
  },
  {
    slug: "formation-oxygenotherapie",
    title: "Formation SST oxygénothérapie",
    excerpt: "Mise en œuvre de l'oxygénothérapie d'urgence en milieu professionnel : reconnaître une détresse respiratoire, choisir le bon masque, régler le débit, surveiller le patient.",
    image: "/formations/formation-oxygenotherapie.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-07-01T15:16:09",
  },
  {
    slug: "formation-psc-premiers-secours-citoyen",
    title: "Formation PSC — Premier Secours Citoyen",
    excerpt: "PSC (anciennement PSC1) — Premier Secours Citoyen pour tous : alerte, hémorragies, étouffement, PLS, RCP, défibrillateur. Attestation de participation Alertis (le diplôme d'État PSC est réservé aux associations agréées).",
    image: "/formations/formation-psc-premiers-secours-citoyen.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-06-30T12:16:51",
  },
  {
    slug: "formation-recyclage-psc",
    title: "Recyclage PSC — Premier Secours Citoyen",
    excerpt: "Recyclage PSC (anciennement PSC1) pour maintenir vos compétences de Premier Secours Citoyen : mise à jour des techniques et gestes selon les dernières recommandations.",
    image: "/formations/formation-recyclage-psc.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-07-01T16:14:04",
  },
  {
    slug: "formation-recyclage-sst-mac-sst",
    title: "Recyclage SST — MAC SST",
    excerpt: "MAC SST — tous les 24 mois pour conserver la certification de Sauveteur Secouriste du Travail. Mise à jour des gestes et nouveau référentiel INRS V8.",
    image: "/formations/formation-recyclage-sst-mac-sst.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-06-30T10:41:47",
  },
  {
    slug: "formation-sst-sauveteur-secouriste-du-travail",
    title: "Formation SST — Sauveteur Secouriste du Travail",
    excerpt: "SST — Sauveteur Secouriste du Travail, formation INRS obligatoire (R4224-15) dans les ateliers à risques et chantiers > 20 personnes. Certificat valable 24 mois.",
    image: "/formations/formation-sst-sauveteur-secouriste-du-travail.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2025-06-19T17:09:13",
  },
  {
    slug: "formation-appareil-respiratoire-isolant",
    title: "Formation ARI — Appareil Respiratoire Isolant",
    excerpt: "Port et utilisation de l'Appareil Respiratoire Isolant (ARI) : équipement, contrôle, intervention en atmosphère toxique ou sous-oxygénée. Pour équipiers de seconde intervention.",
    image: "/formations/formation-appareil-respiratoire-isolant.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-26T15:56:30",
  },
  {
    slug: "formation-de-formateur-incendie",
    title: "Formation de formateur incendie",
    excerpt: "Devenez formateur incendie interne : pédagogie sur extincteurs, scénarios, animation d'exercices d'évacuation. Diffusez la prévention incendie au plus près du terrain.",
    image: "/formations/formation-de-formateur-incendie.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-07-03T10:04:47",
  },
  {
    slug: "formation-equipier-de-premiere-intervention",
    title: "Formation EPI — Équipier de Première Intervention",
    excerpt: "Formation EPI obligatoire (R4227-39) : intervenir sur un départ de feu avec un extincteur, donner l'alerte, encadrer l'évacuation. Théorie + feu réel ou réalité virtuelle.",
    image: "/formations/formation-equipier-de-premiere-intervention.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-26T14:16:45",
  },
  {
    slug: "formation-equipier-de-seconde-intervention",
    title: "Formation ESI — Équipier de Seconde Intervention",
    excerpt: "Formation ESI pour sites industriels et ICPE : intervention en équipe sur sinistre déclaré, port de l'ARI, utilisation des RIA, attaque coordonnée du feu en attendant les secours.",
    image: "/formations/formation-equipier-de-seconde-intervention.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-26T15:17:56",
  },
  {
    slug: "formation-incendie",
    title: "Formation incendie",
    excerpt: "Formation incendie obligatoire (R4227-28) : manipulation d'extincteurs, classes de feu, conduite à tenir et évacuation. Adaptée à votre établissement et à vos risques.",
    image: "/formations/formation-incendie.png",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-06T10:30:01",
  },
  {
    slug: "formation-incendie-en-creche",
    title: "Formation incendie en crèche",
    excerpt: "Formation incendie spécifique aux crèches (ERP type R) : évacuation d'enfants en bas âge, points de rassemblement, organisation des équipes et exercices semestriels.",
    image: "/formations/formation-incendie-en-creche.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-25T12:45:51",
  },
  {
    slug: "formation-incendie-en-etablissement-recevant-du-public",
    title: "Formation incendie ERP O & R (internat/hôtel)",
    excerpt: "Formation incendie pour ERP (Établissement Recevant du Public) : obligations du Règlement de Sécurité, guide-file, serre-file, accueil des secours, registre de sécurité.",
    image: "/formations/formation-incendie-en-etablissement-recevant-du-public.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-07-02T16:27:03",
  },
  {
    slug: "formation-incendie-en-immeuble-de-grande-hauteur",
    title: "Formation incendie IGH",
    excerpt: "Formation incendie spécifique aux Immeubles de Grande Hauteur (IGH) : compartimentage, désenfumage, ascenseurs prioritaires, intervention du PC sécurité, évacuation par niveaux.",
    image: "/formations/formation-incendie-en-immeuble-de-grande-hauteur.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-07-02T16:37:24",
  },
  {
    slug: "formation-incendie-en-realite-virtuelle",
    title: "Formation incendie en réalité virtuelle",
    excerpt: "Formation incendie immersive en VR : départ de feu simulé en 360°, choix de l'extincteur adapté, conduite à tenir. Aucune fumée, sans risque, idéal en intérieur.",
    image: "/formations/formation-incendie-en-realite-virtuelle.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-26T11:21:45",
  },
  {
    slug: "formation-incendie-en-unite-mobile",
    title: "Formation incendie en unité mobile",
    excerpt: "Camion-école incendie équipé déployé sur votre site : générateur de flammes, fumée froide non-toxique, scénarios variés. Idéal pour sites sensibles sans espace extérieur dédié.",
    image: "/formations/formation-incendie-en-unite-mobile.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-24T12:34:54",
  },
  {
    slug: "formation-incendie-etablissements-de-soins-type-j-u",
    title: "Formation incendie ERP J/U (EHPAD/Hôpital)",
    excerpt: "Formation incendie pour EHPAD et établissements de soins (ERP type J et U) : transferts horizontaux, mise en sûreté des résidents non valides, arrêté du 25 juin 1980.",
    image: "/formations/formation-incendie-etablissements-de-soins-type-j-u.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-24T09:58:19",
  },
  {
    slug: "formation-incendie-evacuation-guide-serre-file",
    title: "Formation évacuation — guide-file et serre-file",
    excerpt: "Formation guide-file et serre-file : organiser et sécuriser l'évacuation des locaux, gérer les points de rassemblement, vérifier que personne ne reste à l'intérieur.",
    image: "/formations/formation-incendie-evacuation-guide-serre-file.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-18T16:08:53",
  },
  {
    slug: "formation-manipulation-extincteur",
    title: "Formation manipulation extincteurs (MEX)",
    excerpt: "Apprendre à manipuler un extincteur eau, CO₂ ou poudre face à un feu réel maîtrisé (bac à flammes écologique) : choisir le bon agent, attaquer le feu, sécuriser la zone.",
    image: "/formations/formation-manipulation-extincteur.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-24T15:57:01",
  },
  {
    slug: "formation-premier-temoin-incendie",
    title: "Formation PTI — Premier Témoin Incendie",
    excerpt: "Premier témoin face à un départ de feu : reconnaître les signaux d'alerte, donner l'alerte interne et externe, sécuriser la zone et déclencher la procédure d'évacuation.",
    image: "/formations/formation-premier-temoin-incendie.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-07-03T11:15:41",
  },
  {
    slug: "formation-ssi-systeme-de-securite-incendie",
    title: "Formation SSI — Système de Sécurité Incendie",
    excerpt: "Comprendre et exploiter un Système de Sécurité Incendie (SSI) : détection automatique, mise en sécurité, désenfumage, asservissements, lecture du tableau de signalisation.",
    image: "/formations/formation-ssi-systeme-de-securite-incendie.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2025-06-23T14:00:22",
  },
  {
    slug: "atelier-sensibilisation-gestes-et-postures",
    title: "Atelier sensibilisation gestes et postures",
    excerpt: "Atelier sensibilisation gestes et postures. 45 minutes pour sensibiliser rapidement une équipe aux bons réflexes ergonomiques.",
    image: "/formations/formation-gestes-et-postures.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "exercice-evacuation-incendie",
    title: "Exercice d'évacuation incendie",
    excerpt: "Exercice d'évacuation incendie grandeur nature dans vos locaux. Pour tester votre dispositif et entraîner vos équipes.",
    image: "/formations/formation-incendie-evacuation-guide-serre-file.jpg",
    category: "securite-incendie",
    categoryLabel: "Sécurité incendie",
    categoryHref: "/formations-securite-incendie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-cse-chsct-plus-300",
    title: "Formation CSE CHSCT (+300 salariés) Comité Social Economique - Comité d’Hygiène, de Sécurité, des Conditions de Travail",
    excerpt: "Formation Santé Sécurité Conditions de Travail (SSCT) des membres du CSE pour les entreprises de plus de 300 salariés. Pour maîtriser la mission SSCT héritée de l'ancien CHSCT.",
    image: "/formations/formation-cse-chsct.png",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-centre-commercial-3h",
    title: "Formation gestes et postures centre commercial (3h)",
    excerpt: "Gestes et Postures spécifique centre commercial et grande distribution — format court. Mise en rayon, station debout et manutention en magasin.",
    image: "/formations/gestes-postures-centre-commercial.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-centre-commercial-7h",
    title: "Formation gestes et postures centre commercial (7h)",
    excerpt: "Gestes et Postures spécifique centre commercial et grande distribution — format journée. Analyse de poste, mise en rayon, manutention et prévention TMS.",
    image: "/formations/gestes-postures-centre-commercial.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-conduite",
    title: "Formation gestes et postures conduite",
    excerpt: "Formation Gestes et Postures spécifique à la conduite professionnelle. Pour préserver dos, nuque et épaules face à la station assise prolongée et aux montées/descentes répétées.",
    image: "/formations/gestes-postures-conduite.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-hotellerie-3h",
    title: "Formation gestes et postures hôtellerie (3h)",
    excerpt: "Gestes et Postures spécifique hôtellerie — format court. Réfection des lits, manutention bagages et postures en chambre.",
    image: "/formations/gestes-postures-hotellerie.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-hotellerie-7h",
    title: "Formation gestes et postures hôtellerie (7h)",
    excerpt: "Gestes et Postures spécifique hôtellerie — format journée. Analyse de poste, manutention, réfection des lits et plan de prévention.",
    image: "/formations/gestes-postures-hotellerie.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-nettoyage-3h",
    title: "Formation gestes et postures personnel de nettoyage (3h)",
    excerpt: "Gestes et Postures spécifique au personnel de nettoyage — format court. Manutention matériel, postures basses et gestes répétitifs.",
    image: "/formations/gestes-postures-nettoyage.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-nettoyage-7h",
    title: "Formation gestes et postures personnel de nettoyage (7h)",
    excerpt: "Gestes et Postures spécifique au personnel de nettoyage — format journée. Analyse de poste, manutention, postures et plan de prévention.",
    image: "/formations/gestes-postures-nettoyage.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-preparateur-commande",
    title: "Formation gestes et postures préparateur de commande",
    excerpt: "Formation Gestes et Postures spécifique aux préparateurs de commande. Pour adopter des gestes sûrs face à la manutention répétée et au port de charges en entrepôt.",
    image: "/formations/gestes-postures-preparateur-commande.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-restauration-cuisine-3h",
    title: "Formation gestes et postures restauration et cuisine (3h)",
    excerpt: "Gestes et Postures spécifique restauration et cuisine — format court. Postures de travail, manutention et prévention TMS adaptées au métier.",
    image: "/formations/gestes-postures-restauration-cuisine.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-restauration-cuisine-7h",
    title: "Formation gestes et postures restauration et cuisine (7h)",
    excerpt: "Gestes et Postures spécifique restauration et cuisine — format journée. Analyse des postes, manutention, postures et prévention TMS.",
    image: "/formations/gestes-postures-restauration-cuisine.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-travail-ecran-3h",
    title: "Formation gestes et postures travail sur écran (3h)",
    excerpt: "Formation Gestes et Postures travail sur écran — format court de. Réglages du poste, étirements et prévention de la sédentarité.",
    image: "/formations/gestes-postures-travail-ecran.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gestes-postures-travail-ecran-7h",
    title: "Formation gestes et postures travail sur écran (7h)",
    excerpt: "Formation Gestes et Postures travail sur écran — format journée complète. Analyse de poste, ergonomie, étirements, prévention TMS et fatigue visuelle.",
    image: "/formations/gestes-postures-travail-ecran.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-gqs-initiation-3h",
    title: "Initiation GQS — Gestes Qui Sauvent",
    excerpt: "Initiation Gestes Qui Sauvent. Pour ancrer les bons réflexes face aux urgences vitales — étouffement, hémorragie, arrêt cardiaque.",
    image: "/formations/formation-gqs-gestes-qui-sauvent.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-manutention-personnes-mobilite-reduite",
    title: "Formation manutention des personnes à mobilité réduite",
    excerpt: "Formation manutention des personnes à mobilité réduite. Pour maîtriser les techniques sûres de transfert et préserver à la fois le dos du soignant et la dignité de la personne aidée.",
    image: "/formations/formation-gestes-et-postures-etablissements-de-soins-ehpad.png",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-passerelle-pae-formateur-sst",
    title: "Passerelle PAE vers formateur SST",
    excerpt: "Passerelle PAE vers formateur SST. Pour transformer son expérience pédagogique PAE en habilitation officielle formateur SST INRS.",
    image: "/formations/formation-formateur-sst.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-prevention-tms-sans-visite",
    title: "Formation prévention des TMS sans visite préparatoire",
    excerpt: "Formation Prévention des TMS sans visite préparatoire. Pour comprendre les TMS et adopter les bons gestes au quotidien.",
    image: "/formations/formation-prevention-des-tms-troubles-musculosquelettiques.jpg",
    category: "ergonomie",
    categoryLabel: "Ergonomie",
    categoryHref: "/formations-ergonomie",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-psc-creche-petite-enfance",
    title: "Formation secourisme petite enfance crèche",
    excerpt: "Formation PSC (anciennement PSC1) adaptée petite enfance. Pour maîtriser les gestes de secours spécifiques au nourrisson et à l'enfant.",
    image: "/formations/psc-petite-enfance.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-psc-milieu-professionnel",
    title: "Formation PSC milieu professionnel",
    excerpt: "Formation PSC adaptée milieu professionnel. Pour maîtriser les gestes de premiers secours dans le contexte du lieu de travail.",
    image: "/formations/formation-psc-premiers-secours-citoyen.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-recyclage-psc-creche-petite-enfance",
    title: "Recyclage secourisme petite enfance crèche",
    excerpt: "Recyclage du PSC (anciennement PSC1) petite enfance. 3h30 pour réactualiser les gestes spécifiques nourrisson/enfant et intégrer les évolutions des recommandations.",
    image: "/formations/psc-petite-enfance.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-recyclage-psc-milieu-professionnel",
    title: "Formation PSC milieu professionnel",
    excerpt: "Recyclage du PSC milieu professionnel. 3h30 pour réactualiser les gestes acquis et intégrer les évolutions des recommandations.",
    image: "/formations/formation-recyclage-psc.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-travail-hauteur-port-epi",
    title: "Formation travail en hauteur - port des EPI",
    excerpt: "Formation Travail en Hauteur — port des EPI antichute. Pour travailler en sécurité au-dessus de 2 mètres avec harnais, longes et ligne de vie.",
    image: "/formations/formation-travaux-en-hauteur.png",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-travail-hauteur-port-harnais",
    title: "Formation travail en hauteur - port du harnais",
    excerpt: "Formation Travail en Hauteur — port du harnais antichute. Mise en place et utilisation correcte du harnais.",
    image: "/formations/travail-hauteur-harnais.jpg",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-travail-hauteur-verification-epi",
    title: "Formation travail en hauteur - vérification des EPI",
    excerpt: "Formation Travail en Hauteur — vérification des EPI antichute. Pour devenir vérificateur interne des EPI dans son entreprise.",
    image: "/formations/travail-hauteur-verification-epi.jpg",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "habilitation-electrique-vehicule-electrique",
    title: "Habilitation électrique véhicule électrique (VE)",
    excerpt: "Habilitation électrique Véhicule Électrique (VE). Pour intervenir en sécurité sur les véhicules électriques et hybrides — automobile, utilitaires, deux-roues.",
    image: "/formations/habilitation-electrique-vehicule.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "recyclage-habilitation-electrique-haute-tension",
    title: "Recyclage Habilitation électrique haute tension (B1v B2v BR BC BE / H1v H2v HC)",
    excerpt: "Recyclage de l'habilitation électrique haute tension. Pour conserver les titres B1v/B2v/BR/BC/BE et H1v/H2v/HC.",
    image: "/formations/recyclage-habilitation-electrique-br-b1-b2-bc.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "recyclage-habilitation-electrique-vehicule-electrique",
    title: "Recyclage Habilitation électrique véhicule électrique (VE)",
    excerpt: "Recyclage de l'habilitation électrique VE, tous les 3 ans pour conserver son titre d'habilitation et intégrer les évolutions normatives.",
    image: "/formations/habilitation-electrique-vehicule.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "habilitation-electrique-haute-tension",
    title: "Habilitation électrique haute tension (B1v B2v BR BC BE / H1v H2v HC)",
    excerpt: "Habilitation HTA initiale pour électriciens intervenant en basse et haute tension : travaux, interventions, consignation. Conforme NF C18-510.",
    image: "/formations/habilitation-electrique-h0-b0.jpg",
    category: "habilitation-electrique",
    categoryLabel: "Habilitation électrique",
    categoryHref: "/formations-habilitation-electrique",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-recyclage-sst-oxygenotherapie",
    title: "Recyclage SST oxygénothérapie (MAC SST oxy)",
    excerpt: "MAC SST oxygénothérapie tous les 24 mois pour maintenir la certification SST oxy. Réactualisation des gestes, mise à jour des recommandations et utilisation du matériel d'oxygénothérapie.",
    image: "/formations/formation-oxygenotherapie.jpg",
    category: "secourisme",
    categoryLabel: "Secourisme",
    categoryHref: "/formations-secourisme",
    date: "2026-05-19T10:00:00",
  },
  {
    slug: "formation-prevention-incivilites-conflits-clients",
    title: "Prévention et gestion des incivilités et conflits clients",
    excerpt: "Formation RPS / QVT pour personnels en contact avec le public : prévenir et gérer les incivilités, désamorcer les conflits, protéger sa santé psychologique. Approches concrètes adaptées aux métiers d'accueil et de service.",
    image: "/categories/prevention.jpg",
    category: "prevention",
    categoryLabel: "Prévention",
    categoryHref: "/formations-prevention",
    date: "2026-05-19T10:00:00",
  },
];

export const formationEntriesBySlug = Object.fromEntries(
  formationEntries.map((f) => [f.slug, f] as const)
);

/**
 * Formations retirées du catalogue : leur entrée et leur contenu restent dans
 * le code (pour ne pas perdre les données), mais elles n'apparaissent plus
 * dans aucun listing et leur URL redirige vers la catégorie parente.
 */
export const HIDDEN_FORMATION_SLUGS: ReadonlySet<string> = new Set([
  "formation-de-formateur-incendie",
  "formation-equipier-de-seconde-intervention",
  "formation-incendie-en-immeuble-de-grande-hauteur",
  "formation-gqs-gestes-qui-sauvent",
  "formation-psc-milieu-professionnel",
  "formation-recyclage-psc-milieu-professionnel",
]);

export function getFormationsByCategory(category: FormationCategory) {
  return formationEntries.filter((f) => f.category === category);
}

/**
 * Manually-curated hero image for each category (first formation image is often
 * arbitrary). These are absolute URLs to the live WordPress media; the next.config
 * remotePatterns already allowlists alertisformation.com.
 */
const categoryHeroOverride: Partial<Record<FormationCategory, string>> = {
  "securite-incendie": "/categories/securite-incendie.jpg",
  secourisme: "/categories/secourisme.jpg",
  "habilitation-electrique": "/categories/habilitation-electrique.jpg",
  ergonomie: "/categories/ergonomie.jpg",
  prevention: "/categories/prevention.jpg",
  "safety-day": "/categories/safety-day.jpg",
  afgsu: "/formations/formation-afgsu2.jpg",
};

export function getCategoryHeroImage(category: FormationCategory): string {
  if (categoryHeroOverride[category]) return categoryHeroOverride[category]!;
  const first = formationEntries.find((f) => f.category === category);
  return first?.image ?? "";
}
